name: Deploy Static Website to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run build

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 145.223.108.154
          username: u121546743.indigo-quetzal-137652.hostingersite.com
          password: Admin1@binahub.idAdmin1@binahub.id
          port: 21
          protocol: ftp
          local-dir: out/
          server-dir: public_html/